// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateMatching(ctx context.Context, arg CreateMatchingParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteMatching(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	ExistsMatching(ctx context.Context, id string) (bool, error)
	ExistsUser(ctx context.Context, id string) (bool, error)
	// internal/infrastructure/gateway/mysql/sqlc/query/matching.sql
	GetMatching(ctx context.Context, id string) (Matching, error)
	GetMatchingByParticipants(ctx context.Context, arg GetMatchingByParticipantsParams) (Matching, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListMatchingsByUser(ctx context.Context, arg ListMatchingsByUserParams) ([]Matching, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateMatching(ctx context.Context, arg UpdateMatchingParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
